In [1]:
import torch 
import numpy as np

In [41]:
def int_maker(x):
    max_const = 3
    x = max_const*(x + 2)/2
    return torch.round(x)

In [58]:
bs = 32
ic = 1
oc = 1
#inputs = int_maker(torch.randn(bs, ic, 1, 1))
inputs = torch.zeros(bs, ic, 3, 3)
inputs[0, 0, 1, 1] = 3
inputs[0, 0, 0, 0] = 11
#weights = int_maker(torch.randn(ic, oc, 3, 3))

output_ct = torch.nn.functional.conv_transpose2d(inputs, weights)
#output_cn = torch.nn.functional.conv2d(inputs, weights, padding='same')
output_cn = torch.nn.functional.conv2d(inputs, weights, padding='valid')

In [59]:
inputs

tensor([[[[11.,  0.,  0.],
          [ 0.,  3.,  0.],
          [ 0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.],
          [ 0.,  0.,  0.],
          [

In [60]:
weights

tensor([[[[4., 3., 2.],
          [2., 0., 1.],
          [3., -0., 6.]]]])

In [61]:
output_ct


tensor([[[[44., 33., 22.,  0.,  0.],
          [22., 12., 20.,  6.,  0.],
          [33.,  6., 66.,  3.,  0.],
          [ 0.,  9.,  0., 18.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]],


        [[[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0

In [62]:
output_cn

tensor([[[[44.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]],


        [[[ 0.]]]])

In [40]:
print(output_ct.shape)
print(output_ct[...,1:-1,1:-1].shape)

torch.Size([1, 1, 3, 3])
torch.Size([1, 1, 1, 1])


In [104]:
class maxwell_layer:
    def __init__(self, num_filters, h, w):
        self.weights = torch.randn(1, num_filters, h, w)
        #TODO - get a decent frequency
        self.freq = np.pi/2.0
        
    def call(self, x, t):
        print(x.shape)
        pos_divergence = output_ct = torch.nn.functional.conv_transpose2d(x, self.weights)
        print(pos_divergence.shape)
        neg_divergence = torch.nn.functional.conv2d(x, self.weights, padding=(2,2))
        print(neg_divergence.shape)
        osc = np.sin(self.freq*t)
        print('osc: ', osc)
        return x + osc*(neg_divergence - pos_divergence)[...,1:-1,1:-1]
    
my_layer = maxwell_layer(1, 3, 3)
inputs = torch.randn(1, 1, 5, 5)
print('Inputs: ', torch.sum(inputs))
outputs = my_layer.call(inputs, t=1)
print('Outputs: ', torch.sum(outputs))

Inputs:  tensor(5.7043)
torch.Size([1, 1, 5, 5])
torch.Size([1, 1, 7, 7])
torch.Size([1, 1, 7, 7])
osc:  1.0
tensor(-17.5764)
tensor(-17.5764)
Outputs:  tensor(9.4920)


In [76]:
torch.sin(torch.zeros(1))

tensor([0.])

In [136]:
class maxwell_layer:
    def __init__(self, num_filters, h, w):
        self.weights = torch.randn(1, num_filters, h, w)
        #TODO - get a decent starting frequency
        self.freq = np.pi/2.0
        self.num_filters = num_filters
        
    def call(self, x, t):
        print(x.shape)
        x = torch.nn.functional.pad(x, pad=(1,1,1,1))
        print(x.shape)
        neg_divergence = torch.nn.functional.conv2d(x, self.weights, padding='same', groups=self.num_filters)
        print(neg_divergence.shape)
        pos_divergence = output_ct = torch.nn.functional.conv_transpose2d(x[...,1:-1,1:-1], self.weights, groups=self.num_filters)
        print(pos_divergence.shape)
        osc = np.sin(self.freq*t)
        output = x + osc*(neg_divergence - pos_divergence)
        output = output[...,1:-1,1:-1]
        print(output.shape)
        return output
    
my_layer = maxwell_layer(num_filters=1, h=3, w=3)
inputs = torch.randn(1, 1, 256, 256)
print('Inputs: ', torch.sum(inputs))
outputs = my_layer.call(inputs, t=1)
print('Outputs: ', torch.sum(outputs))
for i in range(100):
    before = torch.sum(inputs)
    inputs = my_layer.call(inputs, 1)
    after = torch.sum(inputs)
    print(before, after)


Inputs:  tensor(14.7601)
torch.Size([1, 1, 256, 256])
torch.Size([1, 1, 258, 258])
torch.Size([1, 1, 258, 258])
torch.Size([1, 1, 258, 258])
torch.Size([1, 1, 256, 256])
Outputs:  tensor(137.5990)
torch.Size([1, 1, 256, 256])
torch.Size([1, 1, 258, 258])
torch.Size([1, 1, 258, 258])
torch.Size([1, 1, 258, 258])
torch.Size([1, 1, 256, 256])
tensor(14.7601) tensor(137.5990)
torch.Size([1, 1, 256, 256])
torch.Size([1, 1, 258, 258])
torch.Size([1, 1, 258, 258])
torch.Size([1, 1, 258, 258])
torch.Size([1, 1, 256, 256])
tensor(137.5990) tensor(506.2928)
torch.Size([1, 1, 256, 256])
torch.Size([1, 1, 258, 258])
torch.Size([1, 1, 258, 258])
torch.Size([1, 1, 258, 258])
torch.Size([1, 1, 256, 256])
tensor(506.2928) tensor(-2742.3071)
torch.Size([1, 1, 256, 256])
torch.Size([1, 1, 258, 258])
torch.Size([1, 1, 258, 258])
torch.Size([1, 1, 258, 258])
torch.Size([1, 1, 256, 256])
tensor(-2742.3071) tensor(-17875.9688)
torch.Size([1, 1, 256, 256])
torch.Size([1, 1, 258, 258])
torch.Size([1, 1, 258, 

In [156]:
from torch.autograd import Variable

class maxwell_layer:
    def __init__(self, num_filters, h, w):
        # Generate weights that add up to 1.
        self.weights = Variable(torch.randn(1, num_filters, h, w))
        self.weights = self.weights/torch.sum(self.weights)
        #TODO - get a decent starting frequency
        self.freq = np.pi/2.0
        self.num_filters = num_filters
        print('weights: ', torch.sum(self.weights), self.weights)
        
    def call(self, x, t):        
        #print('x:', x.shape)
        x_ones = torch.ones_like(x)
        neg_divergence = torch.nn.functional.conv2d(x_ones, self.weights, padding='valid', groups=self.num_filters)
        neg_divergence = torch.nn.functional.pad(neg_divergence, pad=(1,1,1,1))
        #print('nd', neg_divergence.shape)
        pos_divergence = output_ct = torch.nn.functional.conv_transpose2d(x_ones[...,1:-1,1:-1], self.weights, groups=self.num_filters)
        #print('pd', pos_divergence.shape)
        osc = np.sin(self.freq*t)
        output = x + osc*(neg_divergence - pos_divergence)
        output = output
        #print(output.shape)
        return output
    
my_layer = maxwell_layer(num_filters=1, h=3, w=3)
#my_layer.weights = int_maker(my_layer.weights)
inputs = torch.randn(1, 1, 10, 10)
print('Inputs: ', torch.sum(inputs))
outputs = my_layer.call(inputs, t=1)
print('Outputs: ', torch.sum(outputs))
for i in range(100):
    #print(inputs)
    before = torch.sum(inputs)
    inputs = my_layer.call(inputs, 1)
    after = torch.sum(inputs)
    print(before, after)


weights:  tensor(1.) tensor([[[[-0.0133, -0.2474,  0.1159],
          [ 0.3239,  0.2558,  0.4652],
          [ 0.0064, -0.3963,  0.4898]]]])
Inputs:  tensor(-5.0834)
Outputs:  tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0834)
tensor(-5.0834) tensor(-5.0835)
tensor(-5.0835) tensor(-5.0835)
tensor(-5.0835) tensor(-5.0835)
tensor(-5.0835) tensor(-5.0835)
tensor(-5.0835) tensor(-5.0835)
tensor(-